// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: f1.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionStatus int32

const (
	PositionStatus_UNKNOWN  PositionStatus = 0
	PositionStatus_ONTRACK  PositionStatus = 1
	PositionStatus_OFFTRACK PositionStatus = 2
)

// Enum value maps for PositionStatus.
var (
	PositionStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "ONTRACK",
		2: "OFFTRACK",
	}
	PositionStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"ONTRACK":  1,
		"OFFTRACK": 2,
	}
)

func (x PositionStatus) Enum() *PositionStatus {
	p := new(PositionStatus)
	*p = x
	return p
}

func (x PositionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_f1_proto_enumTypes[0].Descriptor()
}

func (PositionStatus) Type() protoreflect.EnumType {
	return &file_f1_proto_enumTypes[0]
}

func (x PositionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionStatus.Descriptor instead.
func (PositionStatus) EnumDescriptor() ([]byte, []int) {
	return file_f1_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xyz    uint64         `protobuf:"fixed64,2,opt,name=xyz,proto3" json:"xyz,omitempty"`
	Status PositionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=f1.PositionStatus" json:"status,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_f1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_f1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_f1_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetXyz() uint64 {
	if x != nil {
		return x.Xyz
	}
	return 0
}

func (x *Position) GetStatus() PositionStatus {
	if x != nil {
		return x.Status
	}
	return PositionStatus_UNKNOWN
}

type PositionFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset    int32                `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp int64                `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Position  map[uint32]*Position `protobuf:"bytes,3,rep,name=position,proto3" json:"position,omitempty" protobuf_key:"fixed32,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PositionFrame) Reset() {
	*x = PositionFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_f1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionFrame) ProtoMessage() {}

func (x *PositionFrame) ProtoReflect() protoreflect.Message {
	mi := &file_f1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionFrame.ProtoReflect.Descriptor instead.
func (*PositionFrame) Descriptor() ([]byte, []int) {
	return file_f1_proto_rawDescGZIP(), []int{1}
}

func (x *PositionFrame) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PositionFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PositionFrame) GetPosition() map[uint32]*Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type PositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Start     int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Duration  int64  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *PositionRequest) Reset() {
	*x = PositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_f1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionRequest) ProtoMessage() {}

func (x *PositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_f1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionRequest.ProtoReflect.Descriptor instead.
func (*PositionRequest) Descriptor() ([]byte, []int) {
	return file_f1_proto_rawDescGZIP(), []int{2}
}

func (x *PositionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *PositionRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PositionRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_f1_proto protoreflect.FileDescriptor

var file_f1_proto_rawDesc = []byte{
	0x0a, 0x08, 0x66, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x66, 0x31, 0x22, 0x48,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x79,
	0x7a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x03, 0x78, 0x79, 0x7a, 0x12, 0x2a, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x66,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xcd, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x3b, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x49, 0x0a,
	0x0d, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x66, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x61, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x38, 0x0a, 0x0e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x4e,
	0x54, 0x52, 0x41, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x46, 0x46, 0x54, 0x52,
	0x41, 0x43, 0x4b, 0x10, 0x02, 0x32, 0x3a, 0x0a, 0x02, 0x46, 0x31, 0x12, 0x34, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x66, 0x31, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x66,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x30,
	0x01, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x69, 0x6b, 0x79, 0x64, 0x6e, 0x61, 0x2f, 0x67, 0x6c, 0x2f, 0x66, 0x31, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_f1_proto_rawDescOnce sync.Once
	file_f1_proto_rawDescData = file_f1_proto_rawDesc
)

func file_f1_proto_rawDescGZIP() []byte {
	file_f1_proto_rawDescOnce.Do(func() {
		file_f1_proto_rawDescData = protoimpl.X.CompressGZIP(file_f1_proto_rawDescData)
	})
	return file_f1_proto_rawDescData
}

var file_f1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_f1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_f1_proto_goTypes = []interface{}{
	(PositionStatus)(0),     // 0: f1.PositionStatus
	(*Position)(nil),        // 1: f1.Position
	(*PositionFrame)(nil),   // 2: f1.PositionFrame
	(*PositionRequest)(nil), // 3: f1.PositionRequest
	nil,                     // 4: f1.PositionFrame.PositionEntry
}
var file_f1_proto_depIdxs = []int32{
	0, // 0: f1.Position.status:type_name -> f1.PositionStatus
	4, // 1: f1.PositionFrame.position:type_name -> f1.PositionFrame.PositionEntry
	1, // 2: f1.PositionFrame.PositionEntry.value:type_name -> f1.Position
	3, // 3: f1.F1.position:input_type -> f1.PositionRequest
	2, // 4: f1.F1.position:output_type -> f1.PositionFrame
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_f1_proto_init() }
func file_f1_proto_init() {
	if File_f1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_f1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_f1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_f1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_f1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_f1_proto_goTypes,
		DependencyIndexes: file_f1_proto_depIdxs,
		EnumInfos:         file_f1_proto_enumTypes,
		MessageInfos:      file_f1_proto_msgTypes,
	}.Build()
	File_f1_proto = out.File
	file_f1_proto_rawDesc = nil
	file_f1_proto_goTypes = nil
	file_f1_proto_depIdxs = nil
}
