// Code generated by "stringer -type=File -linecomment=true -output livetiming_str.go"; DO NOT EDIT.

package livetiming

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileSessionInfo-1]
	_ = x[FileDriverList-2]
	_ = x[FilePosition-3]
	_ = x[FileCarData-4]
	_ = x[FileTimingStats-5]
	_ = x[FileLapCount-6]
	_ = x[FileTimingData-7]
	_ = x[FileTimingAppData-8]
	_ = x[FileTeamRadio-9]
}

const _File_name = "SessionInfo.jsonDriverList.jsonStreamPosition.z.jsonStreamCarData.z.jsonStreamTimingStats.jsonStreamLapCount.jsonStreamTimingData.jsonStreamTimingAppData.jsonStreamTeamRadio.jsonStream"

var _File_index = [...]uint8{0, 16, 37, 58, 78, 100, 119, 140, 164, 184}

func (i File) String() string {
	i -= 1
	if i >= File(len(_File_index)-1) {
		return "File(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _File_name[_File_index[i]:_File_index[i+1]]
}
